### ISSUE TITLE
sanskrit support

### ISSUE THREAD

**Issue by dk** [behdad/fribidi#16]
Hello,

I'm trying to support sanskrit using freebidi and it doesn't seem to do the shaping I expect, like harfbuzz does.
For example क ि  should render into ligature कि . Is it possible to do that with fribidi? If not, -- I'm open at trying to produce a patch, -- it is something that fits into the architecture?

Thank you,
Dmitry

**Comment by khaledhosny** [comment]
FriBiDi is an implementation of the Unicode Bidirectional Text algorithm and the Arabic shaping is just an extra (and the API that does it is deprecated). Indic shaping is completely different thing and has to be done at the font level and can’t be done at character level (and so does proper Arabic shaping, not the seriously limited one FriBiDi supports).

In short you have to use HarfBuzz or comparable font shaping engine for Indic, there is no escape.

**Comment by dk** [comment]
Ow, कि is not a single glyph, but a true font-level ligature! That's a whole new level of hell :) Thank you!
