### ISSUE TITLE
Sync freedesktop git repo with this one

### ISSUE THREAD

**Issue by wiiaboo** [behdad/fribidi#6]
If possible, the repository pointed at the main page of Fribidi (http://cgit.freedesktop.org/fribidi/fribidi) should also be sync and updated with this one, since probably lots of people also compile from it.

**Comment by behdad** [comment]
I caused a divergence last night.  Will fix tonight.  Since fdo doesn't allow non-FF, I have to rewrite this branch.

**Comment by behdad** [comment]
All should be clean now.  Thanks.  CC @khaledhosny
